# Intro to Bayesian Statistics Lab

Complete the following set of exercises to solidify your knowledge of Bayesian statistics and Bayesian data analysis.

In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

## 1. Cookie Problem

Suppose we have two bowls of cookies. Bowl 1 contains 30 vanilla cookies and 10 chocolate cookies. Bowl 2 contains 20 of each. You randomly pick one cookie out of one of the bowls, and it is vanilla. Use Bayes Theorem to calculate the probability that the vanilla cookie you picked came from Bowl 1?

In [2]:
def bayes_rule(priors,likelihood):
    marg = sum(np.multiply(priors,likelihood))
    post = np.divide(np.multiply(priors,likelihood),marg)
    return post

In [3]:
# Probability of vanilla cookie from bowl 1
proba = [1/2,1/2]
likelihood = [0.3,0.2] 
bayes_rule(proba,likelihood)
# there is 0.6 chance that it came from Bowl 1

array([0.6, 0.4])

What is the probability that it came from Bowl 2?

In [4]:
proba = [1/2,1/2]
likelihood = [0.3,0.2] 
bayes_rule(proba,likelihood)
#there is 0.4 chance that it came from Bowl 2

array([0.6, 0.4])

What if the cookie you had picked was chocolate? What are the probabilities that the chocolate cookie came from Bowl 1 and Bowl 2 respectively?

In [5]:
bayes_rule(proba,[0.1,0.2])
# there is 0.3 chance that it came from Bowl 1 & 0.2 chance that it came from Bowl 2

array([0.33333333, 0.66666667])

## 2. Candy Problem

Suppose you have two bags of candies:

- In Bag 1, the mix of colors is:
    - Brown - 30%
    - Yellow - 20%
    - Red - 20%
    - Green - 10%
    - Orange - 10%
    - Tan - 10%
    
- In Bag 2, the mix of colors is:
    - Blue - 24%
    - Green - 20%
    - Orange - 16%
    - Yellow - 14%
    - Red - 13%
    - Brown - 13%
    
Not knowing which bag is which, you randomly draw one candy from each bag. One is yellow and one is green. What is the probability that the yellow one came from the Bag 1?

*Hint: For the likelihoods, you will need to multiply the probabilities of drawing yellow from one bag and green from the other bag and vice versa.*

In [ ]:
'''
A = probability of yellow coming from bag 1
B = probability of yellow + green 
P(B|A) = probability of choosing yelow + green when yellow is from bag 1
'''


In [7]:
print('yellow candy : ', bayes_rule(proba,[0.2,0.14]))
# yellow candy :  [0.58823529 0.41176471]
print('green candy : ',bayes_rule(proba,[0.1,0.2]))
# green candy :  [0.33333333 0.66666667]

yellow candy :  [0.58823529 0.41176471]
green candy :  [0.33333333 0.66666667]


In [33]:
# CORRECTION
priori = [1/2,1/2]
lkl = [0.2*0.2,0.1*0.14]
bayes_rule(priori,lkl)[0]

0.7407407407407408

What is the probability that the yellow candy came from Bag 2?

In [9]:
print('yellow candy from the bag 2 : ', bayes_rule(proba,[0.2,0.14])[1])

yellow candy from the bag 2 :  0.411764705882353


In [34]:
# CORRECTION
bayes_rule(priori,lkl)[1]

0.25925925925925924

What are the probabilities that the green one came from Bag 1 and Bag 2 respectively?

In [10]:
print('green candy : ',bayes_rule(proba,[0.1,0.2]))

green candy :  [0.33333333 0.66666667]


In [35]:
# CORRECTION
priori = [1/2,1/2]
lkl = [0.1*0.14,0.2*0.2]
bayes_rule(priori,lkl)[0]

0.25925925925925924

## 3. Monty Hall Problem

Suppose you are a contestant on the popular game show *Let's Make a Deal*. The host of the show (Monty Hall) presents you with three doors - Door A, Door B, and Door C. He tells you that there is a sports car behind one of them and if you choose the correct one, you win the car!

You select Door A, but then Monty makes things a little more interesting. He opens Door B to reveal that there is no sports car behind it and asks you if you would like to stick with your choice of Door A or switch your choice to Door C. Given this new information, what are the probabilities of you winning the car if you stick with Door A versus if you switch to Door C?

In [37]:
proba = [1/3,1/3,1/3]
likelihood = [0.25,0,0.50] 
bayes_rule(proba,likelihood)

array([0.33333333, 0.        , 0.66666667])

## 4. Bayesian Analysis 

Suppose you work for a landscaping company, and they want to advertise their service online. They create an ad and sit back waiting for the money to roll in. On the first day, the ad sends 100 visitors to the site and 14 of them sign up for landscaping services. Create a generative model to come up with the posterior distribution and produce a visualization of what the posterior distribution would look like given the observed data.

In [41]:
n_draws = 1000
prior = pd.Series(np.random.uniform(0,1,size = n_draws))

In [42]:
def generative_model(param):
    result = np.random.binomial(100,param)
    return result
observed = 14

In [43]:
sim_data = []
for p in prior:
    sim_data.append(generative_model(p))

Produce a set of descriptive statistics for the posterior distribution.

In [44]:
posterior = prior[list (map(lambda x : x == observed,sim_data))]
posterior

27     0.204857
174    0.146536
498    0.095090
503    0.111230
539    0.153399
647    0.189990
820    0.119577
913    0.155436
959    0.207742
974    0.146850
dtype: float64

What is the 90% credible interval range?

In [30]:
print(posterior.quantile(.90))

0.15618245886083926


What is the Maximum Likelihood Estimate?